# Generated by Django 3.2.13 on 2023-02-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230201_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='images/thumbnails/')),
                ('medium', models.ImageField(blank=True, upload_to='images/medium/')),
                ('large', models.ImageField(blank=True, upload_to='images/large/')),
                ('grayscale', models.ImageField(blank=True, upload_to='images/grayscale/')),
            ],
        ),
    ]
