# Generated by Django 3.2.13 on 2023-02-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('thumbnail', models.CharField(blank=True, max_length=255)),
                ('medium', models.CharField(blank=True, max_length=255)),
                ('large', models.CharField(blank=True, max_length=255)),
                ('grayscale', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
