# Generated by Django 3.2.13 on 2023-02-02 10:51

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230201_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagev',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
    ]
